-- CreateTable
CREATE TABLE "Report" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id" STRING NOT NULL,
    "lab_fantazyName" STRING NOT NULL,
    "lab_cnpj" STRING NOT NULL,
    "lab_numberCouncilLab" STRING NOT NULL,
    "lab_state" STRING NOT NULL,
    "lab_cep" STRING NOT NULL,
    "lab_street" STRING NOT NULL,
    "lab_numberStreet" STRING NOT NULL,
    "lab_neighborhood" STRING NOT NULL,
    "lab_additionalInfo" STRING NOT NULL,
    "rt_lab_name" STRING NOT NULL,
    "rt_lab_council" STRING NOT NULL,
    "rt_lab_number_council" STRING NOT NULL,
    "signatory_counsil" STRING NOT NULL,
    "signatory_number_council" STRING NOT NULL,
    "signatory_name" STRING NOT NULL,
    "patient_name" STRING NOT NULL,
    "patient_dateBirth" STRING NOT NULL,
    "patient_gender" STRING NOT NULL,
    "medicalAgreement_cnpj" STRING,
    "medicalAgreement_fantazyName" STRING,
    "doctor_requesting_name" STRING,
    "doctor_requesting_counsil" STRING,
    "doctor_requesting_numCounsil" STRING,
    "exam_body" STRING NOT NULL,
    "exam_name" STRING NOT NULL,
    "exam_date" STRING NOT NULL,
    "report_date" STRING NOT NULL,
    "report_state" STRING NOT NULL,
    "price" STRING NOT NULL,
    "paid" BOOL NOT NULL DEFAULT false,
    "ative" BOOL NOT NULL DEFAULT true,

    CONSTRAINT "Report_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Employee" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id" STRING NOT NULL,
    "login" STRING NOT NULL,
    "password" STRING NOT NULL,
    "name" STRING NOT NULL,
    "dateInative" STRING,
    "role_id" INT4 NOT NULL,
    "counsil" STRING,
    "number_council" STRING,
    "medical_specialty" STRING,
    "signatory" STRING,
    "newPassWord" BOOL NOT NULL DEFAULT true,
    "active" BOOL NOT NULL DEFAULT true,

    CONSTRAINT "Employee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Role" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "role" STRING NOT NULL,
    "access" STRING NOT NULL,

    CONSTRAINT "Role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClientLaboratory" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    "cnpj" STRING,
    "councilLab" STRING,
    "numberCouncilLab" STRING,
    "fantazyName" STRING,
    "socialReason" STRING,
    "state" STRING,
    "cep" STRING,
    "street" STRING,
    "number" STRING,
    "neighborhood" STRING,
    "additionalInfo" STRING,
    "nameTechnicalManager" STRING,
    "council_Tec_Manager" STRING,
    "number_Council_Tec_Manager" STRING,
    "nameFinancialManager" STRING,
    "email" STRING,
    "phone" STRING,
    "paymentBlock" BOOL NOT NULL DEFAULT false,
    "adminBlock" BOOL NOT NULL DEFAULT false,
    "active" BOOL NOT NULL DEFAULT true,

    CONSTRAINT "ClientLaboratory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MedicalAgreement_ExamModel" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id_MedicalAgreement" STRING NOT NULL,
    "id_exam_model" STRING NOT NULL,
    "id" STRING NOT NULL,

    CONSTRAINT "MedicalAgreement_ExamModel_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Exam_Model" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id" STRING NOT NULL,
    "exam_code" STRING NOT NULL,
    "name" STRING NOT NULL,
    "deadline_days" STRING NOT NULL,
    "price" STRING NOT NULL,
    "exam_body" STRING NOT NULL,
    "internet_delivery" BOOL NOT NULL DEFAULT false,

    CONSTRAINT "Exam_Model_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MedicalAgreement" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id" STRING NOT NULL,
    "cnpj" STRING,
    "fantazyName" STRING,
    "socialReason" STRING,
    "state" STRING,
    "cep" STRING,
    "street" STRING,
    "number" STRING,
    "neighborhood" STRING,
    "additionalInfo" STRING,
    "technicalManager" STRING,
    "financialManager" STRING,
    "email" STRING,
    "phone" STRING,

    CONSTRAINT "MedicalAgreement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Doctor" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id" STRING NOT NULL,
    "name" STRING NOT NULL,
    "typeDoctor" STRING NOT NULL,
    "council" STRING NOT NULL,
    "numberCouncil" STRING NOT NULL,
    "active" BOOL NOT NULL DEFAULT true,
    "dateInative" STRING,

    CONSTRAINT "Doctor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subscription" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id" STRING NOT NULL,
    "date" STRING NOT NULL,
    "paid" STRING NOT NULL,
    "paymentType" STRING NOT NULL,

    CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id_clientLaboratory","date","id")
);

-- CreateTable
CREATE TABLE "Patient" (
    "id_clientLaboratory" INT4 NOT NULL,
    "id" STRING NOT NULL,
    "id_medicalAgreement" STRING,
    "name" STRING NOT NULL,
    "dateBirth" STRING NOT NULL,
    "gender" STRING NOT NULL,
    "cpf" STRING,
    "email" STRING,
    "phone" STRING,
    "socialName" STRING,

    CONSTRAINT "Patient_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Report_id_clientLaboratory_idx" ON "Report"("id_clientLaboratory");

-- CreateIndex
CREATE UNIQUE INDEX "Employee_login_key" ON "Employee"("login");

-- CreateIndex
CREATE INDEX "Employee_role_id_idx" ON "Employee"("role_id");

-- CreateIndex
CREATE INDEX "Employee_id_clientLaboratory_idx" ON "Employee"("id_clientLaboratory");

-- CreateIndex
CREATE UNIQUE INDEX "ClientLaboratory_cnpj_key" ON "ClientLaboratory"("cnpj");

-- CreateIndex
CREATE INDEX "MedicalAgreement_ExamModel_id_clientLaboratory_idx" ON "MedicalAgreement_ExamModel"("id_clientLaboratory");

-- CreateIndex
CREATE INDEX "MedicalAgreement_ExamModel_id_MedicalAgreement_idx" ON "MedicalAgreement_ExamModel"("id_MedicalAgreement");

-- CreateIndex
CREATE INDEX "MedicalAgreement_ExamModel_id_exam_model_idx" ON "MedicalAgreement_ExamModel"("id_exam_model");

-- CreateIndex
CREATE UNIQUE INDEX "MedicalAgreement_ExamModel_id_clientLaboratory_id_exam_mode_key" ON "MedicalAgreement_ExamModel"("id_clientLaboratory", "id_exam_model", "id_MedicalAgreement");

-- CreateIndex
CREATE INDEX "MedicalAgreement_id_clientLaboratory_idx" ON "MedicalAgreement"("id_clientLaboratory");

-- CreateIndex
CREATE INDEX "Doctor_id_clientLaboratory_idx" ON "Doctor"("id_clientLaboratory");

-- CreateIndex
CREATE INDEX "Subscription_id_clientLaboratory_idx" ON "Subscription"("id_clientLaboratory");

-- CreateIndex
CREATE INDEX "Patient_id_clientLaboratory_idx" ON "Patient"("id_clientLaboratory");

-- CreateIndex
CREATE INDEX "Patient_id_medicalAgreement_idx" ON "Patient"("id_medicalAgreement");

-- AddForeignKey
ALTER TABLE "Report" ADD CONSTRAINT "Report_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalAgreement_ExamModel" ADD CONSTRAINT "MedicalAgreement_ExamModel_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalAgreement_ExamModel" ADD CONSTRAINT "MedicalAgreement_ExamModel_id_MedicalAgreement_fkey" FOREIGN KEY ("id_MedicalAgreement") REFERENCES "MedicalAgreement"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalAgreement_ExamModel" ADD CONSTRAINT "MedicalAgreement_ExamModel_id_exam_model_fkey" FOREIGN KEY ("id_exam_model") REFERENCES "Exam_Model"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Exam_Model" ADD CONSTRAINT "Exam_Model_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalAgreement" ADD CONSTRAINT "MedicalAgreement_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Doctor" ADD CONSTRAINT "Doctor_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Patient" ADD CONSTRAINT "Patient_id_clientLaboratory_fkey" FOREIGN KEY ("id_clientLaboratory") REFERENCES "ClientLaboratory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Patient" ADD CONSTRAINT "Patient_id_medicalAgreement_fkey" FOREIGN KEY ("id_medicalAgreement") REFERENCES "MedicalAgreement"("id") ON DELETE SET NULL ON UPDATE CASCADE;
